local MER, F, E, L, V, P, G = unpack(select(2, ...))
local options = MER.options.modules.args
local module = MER:GetModule('MER_Bags')
local MERBI = MER:GetModule('MER_BagInfo')

local function updateBagSortOrder()
	SetSortBagsRightToLeft(E.db.mui.bags.BagSortMode == 1)
end

options.bags = {
	type = "group",
	name = E.Retail and E.NewSign .. L["Bags"] or L["Bags"],
	-- hidden = not E.Retail,
	args = {
		header = {
			order = 0,
			type = "header",
			name = F.cOption(L["Bags"], 'orange'),
		},
		Enable = {
			order = 1,
			type = "toggle",
			name = L["Enable"],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; E:StaticPopup_Show("PRIVATE_RL"); end,
			hidden = not E.Retail,
			width = "full",
		},
		spacer = {
			order = 2,
			type = "description",
			name = "",
			fontSize = "medium",
			hidden = not E.Retail,
		},
		header1 = {
			order = 3,
			type = "description",
			name = L["BANK_DESC"],
			hidden = not E.Retail,
		},
		ItemFilter = {
			order = 4,
			type = "multiselect",
			name = L["Item Filter"],
			get = function(_, key) return E.db.mui.bags[key] end,
			set = function(_, key, value) E.db.mui.bags[key] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
			values = {
				FilterJunk = L["Junk"],
				FilterConsumable = L["Consumable"],
				FilterAzerite = L["Azerite"],
				FilterEquipment = L["Equipments"],
				FilterEquipSet = L["EquipSets"],
				FilterLegendary = L["Legendarys"],
				FilterCollection = L["Collection"],
				FilterFavourite = L["Favorite"],
				FilterGoods = L["Goods"],
				FilterQuest = L["Quest"],
				FilterAnima = L["Anima"],
				FilterRelic = L["Relic"],
			},
		},
		GatherEmpty = {
			order = 5,
			type = "toggle",
			name = L["Collect Empty Slots"],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		SpecialBagsColor = {
			order = 6,
			type = "toggle",
			name = L["Special Bags Color"],
			desc = L["|nShow color for special bags:|n- Herb bag|n- Mining bag|n- Gem bag|n- Enchanted mageweave pouch"],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		ShowNewItem = {
			order = 7,
			type = "toggle",
			name = L["New Item Glow"],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		BagsiLvl = {
			order = 8,
			type = "toggle",
			name = L["Show ItemLevel"],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		PetTrash = {
			order = 9,
			type = "toggle",
			name = L["Pet Trash Currencies"],
			desc = L["|nIn patch 9.1, you can buy 3 battle pets by using specific trash items. Keep this enabled, will sort these items into Collection Filter, and won't be sold by auto junk selling."],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		CenterText = {
			order = 10,
			type = "toggle",
			name = L["Center Text"],
			desc = L["Displays additional Infos for an item: e.g. Anima amount"],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		iLvlToShow = {
			order = 11,
			type = "range",
			name = L["ItemLevel Threshold"],
			min = 1, max = 500, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllBags() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		BagSortMode = {
			order = 12,
			type = "select",
			name = L["BagSort Mode"],
			desc = L["|nIf you have empty slots after bag sort, please disable bags module, and turn off all bags filter in default ui containers."],
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; updateBagSortOrder() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
			values = {
				[1] = L["Forward"],
				[2] = L["Backwards"],
				[3] = _G.DISABLE,
			}
		},
		spacer1 = {
			order = 13,
			type = "description",
			name = "",
			hidden = not E.Retail,
		},
		BagsPerRow = {
			order = 14,
			type = "range",
			name = L["Bags per Row"],
			desc = L["|nIf Bags ItemFilter enabled, change the bags per row for anchoring."],
			min = 1, max = 20, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllAnchors() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		BankPerRow = {
			order = 15,
			type = "range",
			name = L["Bank bags per Row"],
			desc = L["|nIf Bags ItemFilter enabled, change the bank bags per row for anchoring."],
			min = 1, max = 20, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateAllAnchors() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		IconSize = {
			order = 16,
			type = "range",
			name = L["Icon Size"],
			min = 20, max = 50, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateBagSize() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		FontSize = {
			order = 17,
			type = "range",
			name = L["Font Size"],
			min = 10, max = 50, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateBagSize() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		BagsWidth = {
			order = 18,
			type = "range",
			name = L["Bags Width"],
			min = 10, max = 40, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateBagSize() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		BankWidth = {
			order = 19,
			type = "range",
			name = L["Bank Width"],
			min = 10, max = 40, step = 1,
			get = function(info) return E.db.mui.bags[info[#info]] end,
			set = function(info, value) E.db.mui.bags[info[#info]] = value; module:UpdateBagSize() end,
			disabled = function() return not E.db.mui.bags.Enable end,
			hidden = not E.Retail,
		},
		equipManager = {
			order = 40,
			type = "group",
			guiInline = true,
			name = F.cOption(L["Equip Manager"], 'orange'),
			hidden = function() return not E.private.bags.enable end,
			args = {
				equipOverlay = {
					order = 1,
					type = "toggle",
					name = L["Equipment Set Overlay"],
					desc = L["Show the associated equipment sets for the items in your bags (or bank)."],
					get = function(info) return E.db.mui.bags.equipOverlay end,
					set = function(info, value) E.db.mui.bags.equipOverlay = value; MERBI:ToggleSettings(); end,
				},
			},
		},
	},
}

