local MER = unpack(ElvUI_MerathilisUI)

MER.Changelog[723] = {
	RELEASE_DATE = "TBD",
	FIXES = {
		"[Core]: Take account of recent ElvUI loading changes",
		"[Core]: Fixed AFK loading changes",
		"[Profile]: Updated Profile encoding/decoding to the new Blizzard API",
		"[Core]: Fixed usage of E.Initialized instead of the outdated E.initialized",
		"[Core]: Fixed compatibility with recent ElvUI changes",
	},
	NEW = {},
	IMPROVEMENTS = {
		"[BigWigs]: Updated the bundled BigWigs profile",
		"[mMediaTag]: Switched back to mMedia Tag & Tools now that it's available again",
		"[Core]: Removed the LibAnim dependency",
		"[Core]: Modules now register themselves on PLAYER_LOGIN to match ElvUI's new loading process",
		"[Locale]: Updated and cleaned up locale files, aligned with the enUS keys",
		"[Core]: Updated several SetFont calls",
		"[Options]: More icons for several options and general options updates",
		"[Core]: Use the new C_EncodingUtil API globals instead of LibDeflate",
		"[Skins]: Various optimizations",
		"[Armory]: Small improvements",
		"[SpecBar]: Minor updates",
		"[GameMenu]: Various improvements",
		"[Misc]: Removed unused FunStuff module and other unneeded code",
		"[ItemLevel]: Updated module",
		"[Notification]: Updated module",
		"[Panels]: Updated module",
		"[Theme]: Updated theme code",
		"[Style]: Code optimizations",
		"[NameHover]: Updated module",
		"[EquipManager]: Updated module",
		"[Options]: Small options optimizations",
		"[Core]: General performance optimizations",
	},
}
