local MER = unpack(ElvUI_MerathilisUI)

MER.Changelog[733] = {
	RELEASE_DATE = "TBD",
	FIXES = {
		"Bags: Categorized Bags - fixed right-click equipping an item instead of selling it while a merchant was open.",
		"Bags: Categorized Bags - fixed expansion/equipment-set sub-headers within a category being nearly invisible.",
		"Bags: Categorized Bags - fixed the Bag Bar popout only showing 3 of 5 possible Warband Bank tabs instead of all 5 (purchased, next purchasable, or locked).",
		"Bags: Categorized Bags - fixed Bank category rows sometimes not responding to clicks when many bank/Warband tabs were listed.",
		"Bags: Categorized Bags - fixed tooltips and other addons' frames anchored to the bags (e.g. Plumber) appearing at the far left of the screen while the bags were open.",
		"Bags: Categorized Bags - fixed a multi-second freeze when sorting a full inventory (bag refreshes are now throttled).",
		"Loot Roll: fixed disabling the Loot Roll module also suppressing ElvUI's own default loot roll frame, leaving no loot roll UI visible at all.",
	},
	NEW = {
		"Mail: added a Postal-style selection bar to the inbox with numbered checkboxes to open or delete multiple mails at once.",
		"Mail: added send templates (recipients/subject/body) with a quick \"Send Templates\" button on the send-mail frame.",
		"Mail: added a quick-attach bar for trade goods (Cloth, Leather, Herb, ...) on the send-mail frame, with a per-category default recipient.",
		"Bags: added a Categorized Bags view (sidebar with default/custom categories, Pinned/Recent items, search) as an alternative to ElvUI's default bag frame. Enabled by default for new profiles; existing profiles keep it off unless enabled manually. Requires a UI reload after enabling/disabling.",
		"Bags: Categorized Bags - added item level and bind-status indicators on slots, each with its own font/size/outline/position options.",
		"Bags: Categorized Bags - added custom icons for user-defined categories (right-click a category and choose Change Icon).",
		"Bags: Categorized Bags - added drag & drop reordering of sidebar categories.",
		"Bags: Categorized Bags - added tracked currencies to the footer, next to gold.",
		"Bags: Categorized Bags - added a Vendor Grays button that sells all grey items at once while at a merchant.",
		"Bags: Categorized Bags - added a Bag view mode that groups items by physical bag instead of category.",
		"Bags: Categorized Bags - added category groups (e.g. \"Equipment\" merges Weapons & Trinkets, Armor and Item Set Gear into one section), with a right-click Rename/Disband Group/Ungroup/Hide-in-All-Items menu.",
		"Bags: Categorized Bags - added quest, crafted-item quality, and Pawn upgrade-arrow icons on item slots, plus a vendor sell-cursor when hovering an item at a merchant.",
		"Bags: Categorized Bags - added Shift+Right-click Split Stack support on item slots.",
		"Bags: Categorized Bags - item slots now show the same Equipment Manager set icon as ElvUI's own bag slots.",
		"Bags: Categorized Bags - added a cross-character gold tooltip on the footer's gold display (every known character's gold, account total, and Warband Bank balance).",
		"Bags: Categorized Bags - added Bank and Warband Bank support that opens automatically with the bank, per-tab filtering, right-click tab settings, and a buy-next-tab prompt.",
		"Bags: Categorized Bags - the Bank and Warband Bank now open in their own dedicated window with a tab-based sidebar, a footer showing player and Warband gold with Withdraw/Deposit buttons, and a relabeling Auto Deposit button; opening it also opens the bag window alongside it.",
		"Bags: Categorized Bags - added a tooltip on hover for sidebar categories, showing the name and item count (most useful with a collapsed sidebar).",
		"Bags: Categorized Bags - added Item Set Gear, Gear Enhancements, Professions, and Housing categories, and merged Recipes into Professions.",
		"Bags: Categorized Bags - added drag-to-assign \"+\" slots at the end of every category: drag an item onto one to assign it to that category (or pin it, for Pinned Items).",
		"Bags: Categorized Bags - section headers can now be collapsed by clicking them (remembered per category); clicking a collapsed category in the sidebar unfolds it.",
		"Bags: Categorized Bags - added a right-click menu for default categories (Rename, Reset Name, Hide/Show in All Items).",
		"Bags: Categorized Bags - added a pulsing new-item glow, a Warbound/Warbound-until-equipped marker (plus \"WuE\" bind text), and a Sort spinner matching ElvUI's own bags.",
		"Bags: Categorized Bags - added an Effects options tab (window fade, new-item glow, slot hover color, empty-slot opacity, Warbound marker, custom window opacity).",
	},
	IMPROVEMENTS = {
		"Options: scrollbars on MerathilisUI's own options pages now use a slimmer, accent-colored thumb instead of ElvUI's general value color.",
		"Bags: Categorized Bags - added ElvUI-style Sort/Stack/Help buttons to the title bar.",
		"Bags: Categorized Bags - added more layout options (item spacing, header height, sidebar row height, spacing between categories).",
		"Bags: Categorized Bags - added an alternating sidebar row background, matching the Armory panel's stat rows.",
		"Bags: Categorized Bags - right-clicking an item while a merchant is open now sells it (including equipment) instead of using/equipping it.",
		"Bags: Categorized Bags - the Bank's content is now grouped by physical tab (with flat OneBank/OneWarband views) instead of by category.",
		"Bags: Categorized Bags - removed the separate Junk category; grey/sellable items now sort into their normal category instead.",
		"Bags: Categorized Bags - polished visuals: header divider lines, class-colored accents (scrollbar, hover overlays, selected rows, sub-headers), dimmed counts, window fade-in/out, a fill-level bar with a colored item counter (yellow from 80%, red from 95%), a search result count, and an empty-state message.",
	},
}
