local MER = unpack(ElvUI_MerathilisUI)

MER.Changelog[737] = {
	RELEASE_DATE = "TBD",
	FIXES = {
		"[ActionBars]: Color Modifier Keys can be turned on and off without a reload, turning it off or switching profiles works right away now.",
		"[AFK]: The AFK screen is now really turned off while BenikUI is enabled, as the option always described, and the option shows the reason.",
		'[Armory]: Enchant texts and stat labels no longer show broken icon codes (e.g. "A:Professions-...") after their colors were removed.',
		"[Armory]: The Missing Sockets tooltip no longer throws a Lua error.",
		"[Armory]: The outline setting of the header texts (name, title, level, class, spec icon) works now, and Class Gradient for the title text is applied.",
		"[Armory/Equipment Manager]: With a custom header or label font color, the dividers and row gradients stayed white instead of using that color.",
		"[Armory/Socket Panel]: Inserting a gem through the socket panel on the Character Frame works now, before it silently did nothing.",
		"[Auras]: The collapsed state of the buffs is kept when the Collapse & Expand button is turned off and on again, and a profile switch uses the state of the new profile.",
		"[Bags]: Changes to the equipment set icon show up in the categorized bags right away, and the item font options repaint the bank as well.",
		"[Buff Reminder]: The reminder sound no longer repeats for reminders that were already shown, and a muted category no longer blocks the sound of the others.",
		"[Buff Reminder]: Turning the module off or switching to a profile where it is off hides the icons right away.",
		"[Changelog]: /mer changelog and the chat link open the changelog page again instead of only the options start page.",
		"[Chat Edit Box]: The chat type badge text was unreadable on bright chat colors like Whisper or Say, because the dark text kept a black outline.",
		"[Chat Sidebar]: With the edit box inside the chat panel, the edit box no longer covers the sidebar.",
		"[Commands]: The hints of /mer (usage, missing MerathilisUI profile) are shown again, they were hidden behind a WindTools log setting.",
		'[Core]: Fixed possible Lua errors in combat ("secret value") in color comparisons, color gradients and name abbreviations.',
		"[Core]: Fixed Lua errors when MerathilisUI tried to report an internal problem (e.g. a missing media file, category icon or skin element).",
		"[Core]: Class gradient texts now fully reach their end color on the last letter.",
		"[Core]: Fixed modules losing combat events (e.g. the Armory update after combat) when another module was turned off or updated.",
		"[Core]: Clicking the Open Changelog link in the chat no longer also opens an empty link tooltip.",
		"[Core]: A fresh install no longer prints Update Database messages, and update messages only appear when something changed, in the right order.",
		"[Core]: Buff Reminder, Copy Transmog, Movement Alert, Portal Flyout, Singing Sockets, Trade Tabs, Tracker and Vehicle Bar no longer use deprecated Blizzard functions, which only exist while Blizzard's deprecation fallbacks are enabled.",
		'[Cursor]: The GCD and cast rings no longer throw Lua errors ("secret value") during Mythic+ and raid encounters.',
		'[Cursor]: With "Only While Steering Camera" the ring no longer shows up after the module was turned off.',
		"[Debug Mode]: /muidebug off can re-enable the disabled addons again after logging out and back in, the list was cleared on every login.",
		"[Durability/ItemLevel Datatext]: Fixed Lua errors with low durability when the icon is colored or the colored thresholds are enabled.",
		"[ElvUI AuraBars]: MerathilisUI no longer replaces ElvUI's name abbreviation, so the aura bars abbreviate spell names the ElvUI way again.",
		"[Gradient Theme]: The Saturation Boost can be turned on again, before the toggle had no effect. Its sliders are disabled while it is off.",
		"[Gradient Theme]: The saturation boost settings are now also used for frames without a fixed color.",
		"[Gradient Theme]: The gradient previews in the options update again when colors are changed.",
		"[Installer]: The color preview of the UnitFrames step stuck to other steps, and the step buttons cut off longer labels. Closing the installer no longer leaves MerathilisUI changes behind for the next plugin installer.",
		"[Installer]: Errors while applying a profile are now reported instead of being silently ignored.",
		"[Installer]: The chat step names the combat log window correctly again and uses Blizzard's current chat functions instead of deprecated ones.",
		"[Installer]: Removed the Cooldown Manager checkbox from the Modules step, the module no longer exists.",
		"[Item Level]: Turning the module on or off no longer throws a Lua error.",
		"[Location Panel]: The Disable ElvUI Cluster option asks for the correct reload, and the options of the panel are disabled while it is turned off.",
		"[Loot Roll]: After a profile switch the bars use the settings of the new profile, and an open test preview follows color and direction changes right away.",
		"[Loot Spec Manager]: Fixed a Lua error every time a tab of the Encounter Journal was switched.",
		"[Loot Spec Manager/Copy Transmog]: The info tooltips are colored again.",
		"[Mail]: Switching to a profile with the Mail module turned off (or on) applies right away.",
		"[Minimap Buttons]: Turning the module off hides both bars right away and gives the Blizzard icons back, before it needed a reload.",
		'[Movement Alert]: Fixed a Lua error in combat ("attempt to compare a secret number value") when a tracked spell\'s cooldown is restricted.',
		"[Name Hover]: The line with faction, classification and race is now placed correctly between the guild and the status line.",
		"[Name Hover]: The outline options work now, before every text always used a shadow outline, and the Enemy Forces font size is applied to the text as well.",
		"[Name Hover]: A profile switch applies the settings of the new profile right away, including turning Name Hover on or off.",
		"[NamePlates]: After a profile switch the faction icons on the visible nameplates use the settings of the new profile.",
		"[Notification]: The Vignette Time Out option works now, before it was always 20 seconds, and the font options are applied to every notification.",
		"[Notification]: Adding something that is not a number to the Vignette blacklist no longer throws a Lua error, and removed default IDs stay removed after a reload.",
		"[Options]: Sub-options of the Buff Reminder, the Categorized Bags and the Specialization Bar are disabled as well when their module or the required ElvUI module is turned off.",
		"[Panels]: Changing the height of the top panel no longer throws a Lua error, the Reset of the custom color restores the right color and a profile switch applies the panel settings of the new profile.",
		"[Pet Filter Tab]: The pet filter tab in the Collections window could fail to appear, because it loaded through the same event handler as another feature.",
		'[Portal Flyout]: Fixed Lua errors ("secret value") when opening the flyout or casting during an active Mythic+ key.',
		"[Profiles]: Importing an invalid or damaged string no longer reloads the UI or throws a Lua error, it shows an error message and changes nothing.",
		"[Profiles]: Removed the AddOnSkins button under Profiles > AddOns, it did nothing. The addon buttons have a fixed order now.",
		"[Reset]: The reset buttons in the Advanced settings now fully restore a module's defaults. Entries you added yourself, like blacklist entries or custom categories, were kept before.",
		"[Resting Indicator]: Removed the broken Custom Gradient Color option, it caused a Lua error after login. The indicator always uses the class gradient.",
		"[Scale]: Sync Inspect works, and the Transmog, Class Trainer, Item Upgrade and Equipment Flyout sliders now actually scale their frames.",
		"[Skins]: The ls_Toasts skin can be turned off again, and Mount Route Planner has its own toggle in the AddOnSkins options.",
		"[Skins]: The BugSack skin and the BigWigs queue timer skin now follow the AddOnSkins toggle.",
		"[Tags]: [name:MER:gradient] shows players without a known class again and updates its color when the reaction of an NPC changes.",
		"[UnitFrames]: Removed a leftover call to the old Portraits that stopped the UnitFrames setup with a hidden Lua error.",
		"[Vehicle Bar]: Changed settings apply right away again instead of only after a reload.",
	},
	NEW = {
		"[Cursor]: The GCD and cast rings have the Only In Instances and Only In Combat options as well.",
		"[Developer Tools]: New /muidev command - a copyable log window with version info for bug reports (/muidev log), debug channels per module (/muidev debug <module>), log level and value inspection. Replaces the Tracker debug mode, the Vignette debug print option and /mlrdebug.",
		"[Installer]: New Modules step after UnitFrames - pick which MerathilisUI modules you want to use, applied on the reload at the end.",
		"[Loot Roll]: The font of the loot roll bars can be changed.",
		"[Profiles]: The General tab has real font options now - pick a replacement font and outline for the main font and the number font, and a size offset for all fonts. Apply writes them into the ElvUI profile.",
		"[Tracker]: New module - a Battle Res tracker shows the shared battle res charges of your group and the time until the next charge during Mythic+ keys and raid boss encounters, as an icon or as a compact text line. A Bloodlust tracker shows your Sated lockout, the active lust and optionally when a lust is ready again.",
		"[UnitFrames/NamePlates]: New Faction Indicator - shows the faction crest of players from the opposing faction on the Target, Focus and Arena frames (Target of Target and Focus Target optional) and on the NamePlates. Style, size and position can be set per frame.",
	},
	IMPROVEMENTS = {
		"[ActionBars]: The Specialization Bar mouseover option applies without a reload.",
		"[Armory]: Font, header and background settings apply right away without a reload.",
		"[Auras]: The Collapse & Expand option is disabled with a notice while ElvUI's buffs are turned off.",
		"[Bags]: The bag options are disabled with a notice while ElvUI's bags are turned off.",
		"[Buff Reminder]: Options that have no effect in the current setup are disabled.",
		"[Core]: Errors while a module starts up are now reported (e.g. in BugSack) instead of being silently ignored.",
		"[Core]: Uses ElvUI's animation library instead of a bundled copy.",
		"[Core]: Removed a lot of unused internal code: helper functions, internal data (a large boss ID list, unused colors, fonts, requirements and duplicate role icon sets), the legacy gradient color settings, unused settings of removed modules and an interrupt check that ran on every spec, level and zone change.",
		"[Core]: Errors of a module while switching profiles are now reported instead of being silently ignored.",
		"[Cursor]: Turning the module on or off works without a reload.",
		"[Gradient Theme]: Several option labels (NPC reactions, cast colors, power colors, fade directions) are translated now.",
		"[Information]: New buttons for the MerathilisUI website on the options start page and in the Information tab. Support & Downloads now also links the MerathilisUI Discord, the Tukui links have their own section.",
		"[Information]: Support & Downloads now points to /muidev log for bug reports, and the translator list has a fixed order.",
		"[Installer]: The final step now points to the MerathilisUI website, with a Website button next to Discord.",
		"[Item Level]: The item level on the equipment flyout, the scrapping machine and in the guild news is now left to WindTools (Item > Item Level, Misc), which did the same and showed it twice. MerathilisUI keeps the item level in the merchant and trade windows, which can be turned off without a reload.",
		"[Login Logo]: The logo no longer shows up while in combat or in an instance, only after the installer has been completed, and it moves more smoothly.",
		"[Login Message]: The login message now also links the MerathilisUI website.",
		"[Mail]: The Mail module can be turned on and off without a reload.",
		"[Misc]: Removed the Fun Stuff option and the old Transmog Frame toggle, they had no effect anymore.",
		"[Movement Alert]: The color, font, sound and text options of the Time Spiral, Gateway Control Shard and Ready Alert sections are disabled while that section is turned off.",
		"[Name Hover]: Font and display options apply without a reload, and the options are disabled while Name Hover is turned off.",
		"[Notification]: All options apply without a reload, only turning the module on still needs one.",
		"[Options]: Pages that are locked because an ElvUI module is turned off or EltruismUI is enabled now show the reason at the top. The Scale tab is no longer hidden with EltruismUI, it is locked instead.",
		"[Reset]: New reset buttons for Chat and NamePlates.",
		"[Skins]: Removed the Action Status font option, it had no effect anymore. WindTools offers the same setting.",
		"[Skins]: The embed options are disabled while the skins or the embed are turned off, and the AddOn skin list has a fixed order.",
		"[Vehicle Bar]: The vigor bar uses the class gradient of the Gradient Theme when the theme is enabled.",
	},
}
