local MER = unpack(ElvUI_MerathilisUI)

MER.Changelog[737] = {
	RELEASE_DATE = "TBD",
	FIXES = {
		'[Armory]: Enchant texts and stat labels no longer show broken icon codes (e.g. "A:Professions-...") after their colors were removed.',
		"[Armory/Equipment Manager]: With a custom header or label font color, the dividers and row gradients stayed white instead of using that color.",
		"[Changelog]: /mer changelog and the chat link open the changelog page again instead of only the options start page.",
		"[Chat Edit Box]: The chat type badge text was unreadable on bright chat colors like Whisper or Say, because the dark text kept a black outline.",
		"[Commands]: The hints of /mer (usage, missing MerathilisUI profile) are shown again, they were hidden behind a WindTools log setting.",
		'[Core]: Fixed possible Lua errors in combat ("secret value") in color comparisons, color gradients and name abbreviations.',
		"[Core]: Fixed Lua errors when MerathilisUI tried to report an internal problem (e.g. a missing media file, category icon or skin element).",
		"[Core]: Class gradient texts now fully reach their end color on the last letter.",
		"[Core]: Fixed modules losing combat events (e.g. the Armory update after combat) when another module was turned off or updated.",
		"[Core]: Clicking the Open Changelog link in the chat no longer also opens an empty link tooltip.",
		"[Core]: A fresh install no longer prints Update Database messages, and update messages only appear when something changed, in the right order.",
		"[Debug Mode]: /muidebug off can re-enable the disabled addons again after logging out and back in, the list was cleared on every login.",
		"[Durability/ItemLevel Datatext]: Fixed Lua errors with low durability when the icon is colored or the colored thresholds are enabled.",
		"[ElvUI AuraBars]: MerathilisUI no longer replaces ElvUI's name abbreviation, so the aura bars abbreviate spell names the ElvUI way again.",
		"[Gradient Theme]: The saturation boost settings are now also used for frames without a fixed color.",
		"[Gradient Theme]: The gradient previews in the options update again when colors are changed.",
		"[Installer]: The color preview of the UnitFrames step stuck to other steps, and the step buttons cut off longer labels. Closing the installer no longer leaves MerathilisUI changes behind for the next plugin installer.",
		"[Installer]: Errors while applying a profile are now reported instead of being silently ignored.",
		"[Installer]: The chat step names the combat log window correctly again and uses Blizzard's current chat functions instead of deprecated ones.",
		"[Installer]: Removed the Cooldown Manager checkbox from the Modules step, the module no longer exists.",
		"[ItemLevel/Pet Filter Tab]: The item level on the Scrapping Machine and the pet filter tab in the Collections window could fail to appear, because both loaded through the same event handler.",
		"[Loot Spec Manager/Copy Transmog]: The info tooltips are colored again.",
		'[Movement Alert]: Fixed a Lua error in combat ("attempt to compare a secret number value") when a tracked spell\'s cooldown is restricted.',
		'[Portal Flyout]: Fixed Lua errors ("secret value") when opening the flyout or casting during an active Mythic+ key.',
		"[Profiles]: Importing an invalid or damaged string no longer reloads the UI or throws a Lua error, it shows an error message and changes nothing.",
		"[Resting Indicator]: Removed the broken Custom Gradient Color option, it caused a Lua error after login. The indicator always uses the class gradient.",
		"[Skins]: The ls_Toasts skin can be turned off again, and Mount Route Planner has its own toggle in the AddOnSkins options.",
		"[Tags]: [name:MER:gradient] shows players without a known class again and updates its color when the reaction of an NPC changes.",
		"[UnitFrames]: Removed a leftover call to the old Portraits that stopped the UnitFrames setup with a hidden Lua error.",
		"[Vehicle Bar]: Changed settings apply right away again instead of only after a reload.",
	},
	NEW = {
		"[Developer Tools]: New /muidev command - a copyable log window with version info for bug reports (/muidev log), debug channels per module (/muidev debug <module>), log level and value inspection. Replaces the Tracker debug mode, the Vignette debug print option and /mlrdebug.",
		"[Installer]: New Modules step after UnitFrames - pick which MerathilisUI modules you want to use, applied on the reload at the end.",
		"[Tracker]: New module - a Battle Res tracker shows the shared battle res charges of your group and the time until the next charge during Mythic+ keys and raid boss encounters, as an icon or as a compact text line. A Bloodlust tracker shows your Sated lockout, the active lust and optionally when a lust is ready again.",
		"[UnitFrames/NamePlates]: New Faction Indicator - shows the faction crest of players from the opposing faction on the Target, Focus and Arena frames (Target of Target and Focus Target optional) and on the NamePlates. Style, size and position can be set per frame.",
	},
	IMPROVEMENTS = {
		"[Core]: Errors while a module starts up are now reported (e.g. in BugSack) instead of being silently ignored.",
		"[Core]: Uses ElvUI's animation library instead of a bundled copy.",
		"[Core]: Removed a lot of unused internal code: helper functions, internal data (a large boss ID list, unused colors, fonts, requirements and duplicate role icon sets), the legacy gradient color settings, unused settings of removed modules and an interrupt check that ran on every spec, level and zone change.",
		"[Core]: Errors of a module while switching profiles are now reported instead of being silently ignored.",
		"[Information]: New buttons for the MerathilisUI website on the options start page and in the Information tab. Support & Downloads now also links the MerathilisUI Discord, the Tukui links have their own section.",
		"[Installer]: The final step now points to the MerathilisUI website, with a Website button next to Discord.",
		"[Login Logo]: The logo no longer shows up while in combat or in an instance, only after the installer has been completed, and it moves more smoothly.",
		"[Login Message]: The login message now also links the MerathilisUI website.",
		"[Options]: Pages that are locked because an ElvUI module is turned off or EltruismUI is enabled now show the reason at the top. The Scale tab is no longer hidden with EltruismUI, it is locked instead.",
		"[Skins]: Removed the Action Status font option, it had no effect anymore. WindTools offers the same setting.",
		"[Vehicle Bar]: The vigor bar uses the class gradient of the Gradient Theme when the theme is enabled.",
	},
}
