local MER = unpack(ElvUI_MerathilisUI)

MER.Changelog[737] = {
	RELEASE_DATE = "TBD",
	FIXES = {
		'[Movement Alert]: Fixed a Lua error in combat ("attempt to compare a secret number value") when a tracked spell\'s cooldown is restricted.',
		"[ItemLevel/Pet Filter Tab]: The item level on the Scrapping Machine and the pet filter tab in the Collections window could fail to appear, because both loaded through the same event handler.",
		"[Chat Edit Box]: The chat type badge text was unreadable on bright chat colors like Whisper or Say, because the dark text kept a black outline.",
		"[Installer]: The color preview of the UnitFrames step stuck to other steps, and the step buttons cut off longer labels. Closing the installer no longer leaves MerathilisUI changes behind for the next plugin installer.",
		'[Core]: Fixed possible Lua errors in combat ("secret value") in color comparisons, color gradients and name abbreviations.',
		"[Loot Spec Manager/Copy Transmog]: The info tooltips are colored again.",
		"[ElvUI AuraBars]: MerathilisUI no longer replaces ElvUI's name abbreviation, so the aura bars abbreviate spell names the ElvUI way again.",
		"[Core]: Fixed Lua errors when MerathilisUI tried to report an internal problem (e.g. a missing media file, category icon or skin element).",
		"[Commands]: The hints of /mer (usage, missing MerathilisUI profile) are shown again, they were hidden behind a WindTools log setting.",
		"[UnitFrames]: Removed a leftover call to the old Portraits that stopped the UnitFrames setup with a hidden Lua error.",
		"[Armory/Equipment Manager]: With a custom header or label font color, the dividers and row gradients stayed white instead of using that color.",
		"[Resting Indicator]: Removed the broken Custom Gradient Color option, it caused a Lua error after login. The indicator always uses the class gradient.",
		"[Gradient Theme]: The saturation boost settings are now also used for frames without a fixed color.",
		'[Armory]: Enchant texts and stat labels no longer show broken icon codes (e.g. "A:Professions-...") after their colors were removed.',
		"[Core]: Class gradient texts now fully reach their end color on the last letter.",
		"[Vehicle Bar]: Changed settings apply right away again instead of only after a reload.",
		"[Gradient Theme]: The gradient previews in the options update again when colors are changed.",
		"[Core]: Fixed modules losing combat events (e.g. the Armory update after combat) when another module was turned off or updated.",
		"[Profiles]: Importing an invalid or damaged string no longer reloads the UI or throws a Lua error, it shows an error message and changes nothing.",
		'[Portal Flyout]: Fixed Lua errors ("secret value") when opening the flyout or casting during an active Mythic+ key.',
	},
	NEW = {
		"[UnitFrames/NamePlates]: New Faction Indicator - shows the faction crest of players from the opposing faction on the Target, Focus and Arena frames (Target of Target and Focus Target optional) and on the NamePlates. Style, size and position can be set per frame.",
		"[Tracker]: New module - a Battle Res tracker shows the shared battle res charges of your group and the time until the next charge during Mythic+ keys and raid boss encounters, as an icon or as a compact text line. A Bloodlust tracker shows your Sated lockout, the active lust and optionally when a lust is ready again.",
		"[Installer]: New Modules step after UnitFrames - pick which MerathilisUI modules you want to use, applied on the reload at the end.",
		"[Developer Tools]: New /muidev command - a copyable log window with version info for bug reports (/muidev log), debug channels per module (/muidev debug <module>), log level and value inspection. Replaces the Tracker debug mode, the Vignette debug print option and /mlrdebug.",
	},
	IMPROVEMENTS = {
		"[Login Logo]: The logo no longer shows up while in combat or in an instance, only after the installer has been completed, and it moves more smoothly.",
		"[Information]: New buttons for the MerathilisUI website on the options start page and in the Information tab. Support & Downloads now also links the MerathilisUI Discord, the Tukui links have their own section.",
		"[Installer]: The final step now points to the MerathilisUI website, with a Website button next to Discord.",
		"[Core]: Removed a lot of unused internal functions and an unused interrupt check that ran on every spec, level and zone change.",
		"[Core]: Errors while a module starts up are now reported (e.g. in BugSack) instead of being silently ignored.",
		"[Core]: Removed unused internal data (a large boss ID list, unused colors, fonts, requirements and duplicate role icon sets).",
		"[Vehicle Bar]: The vigor bar uses the class gradient of the Gradient Theme when the theme is enabled.",
		"[Core]: Removed the unused legacy gradient color settings and color helpers.",
		"[Core]: Uses ElvUI's animation library instead of a bundled copy.",
	},
}
