local MER = unpack(ElvUI_MerathilisUI)

MER.Changelog[740] = {
	RELEASE_DATE = "TBD",
	FIXES = {
		"[AFK]: The chat shows on screen again, the realm time in 12-hour format shows the right AM/PM and the logout timer no longer restarts when your status changes while away.",
		"[Bags]: Opening the categorized bags right after logging in no longer shows Pawn errors while Pawn is still loading.",
		"[Core]: The checkmark in the profile update messages shows again.",
		"[Core]: Switching, copying or resetting a profile updates all MerathilisUI modules again right away instead of after a reload, without errors from the settings of the previous profile.",
		"[Installer]: The changelog popup no longer opens on top of the installer on a fresh install.",
		"[Misc]: The search box in the icon picker shows a real title and tooltip instead of its internal names.",
		"[Name Hover]: Hovering a unit no longer rebuilds the whole text, quest lines and tooltip scan many times a second, only when you move to another unit.",
		"[Notification]: The new mail toast plays a sound again.",
		"[Skins]: The AddOnSkins toggles are now locked while Skins or AddOnSkins are disabled.",
	},
	NEW = {
		"[ActionBars]: Brought back Blizzard's rotation frame on the Single-Button Assistant button, sized for ElvUI's square buttons, with an optional combat animation and class or custom colors.",
		"[Compatibility Check]: After login MerathilisUI checks if Shadow & Light, BenikUI, ToxiUI, Eltruism, mMediaTag & Tools, LuckyoneUI, WindTools or ProjectAzilroka have the same features turned on, and lets you choose per feature which one stays on. It can be turned off or started again under Advanced Settings.",
		"[General]: Added Performance Tuning, a one-click graphics adjustment for a higher frame rate and a sharper image, with a revert button and a details card listing every change.",
		"[NamePlates]: Castbar Shield: a shield icon on the castbars of hostile nameplates while their cast can't be interrupted, so you see at a glance whether you can kick it.",
		"[Quick Grid]: New module: hold a key and a 3x3 grid of actions opens at your cursor, release it in a direction to use one, in combat too. Comes with decks for teleports, travel, markers and professions plus a custom one.",
		"[Skins]: Added a skin for AussyLoot: its window, menus, popups and drop alert get the ElvUI backdrop and shadow and use the ElvUI font, while its own theme colors stay. If the mMediaTag & Tools AussyLoot skin is turned on too, the Compatibility Check lets you choose which one stays.",
		"[Tooltip]: Shows the buffs of hovered players as icons on the tooltip, with position, icon size, icons per row and offset options. The new Tooltip options page also has the achievement link toggle.",
		"[UnitFrames]: Castbar Shield on the castbars of the target, focus, boss and arena frames, the same icon as on the nameplates.",
		"[UnitFrames]: Rounded Corners: the health, power and class bars of the player, target, focus, target of target, pet, pet target, party and raid frames get rounded corners and a rounded border. An attached power bar is rounded together with the health bar as one block.",
		"[Unlock Mode]: New module that extends ElvUI's mover mode with an unlock animation: movers snap to the edges and centers of other movers and the screen with guide lines, Alt-click anchors the selected mover to another one so it follows it, a click selects a mover for pixel-exact arrow key nudging, small movers stay above big ones, the parts still placed by Blizzard's Edit Mode are marked and open it on click, and a toolbar replaces ElvUI's mover window with the layout filter, grid, snapping and a count of your changes, which you can revert before you lock.",
	},
	IMPROVEMENTS = {
		"[AFK]: The AFK screen got more atmosphere: a vignette darkens the world, the panel slides in and the player model fades in, a bar counts down to the logout, and the sleeping model wakes up for a random emote now and then, with rising Z's and changing speech bubble lines while it sleeps.",
		"[Chat]: The resize grips on the chat panels only show while you hover their corner.",
		"[Core]: Font sizes, color shading and the option sliders use ElvUI's clamp function instead of their own copies.",
		"[General]: Lower CPU use: features you turned off no longer register any events, hooks or timers, and the Vehicle Bar vigor bar, the buff collapse button, Chat Sidebar, Movement Alert, Interrupt Ready, Minimap Buttons, Notifications and the equipment set icon in the bags react to game events instead of checking on a timer. The option pages are only built the first time you open the options, which saves memory and loading time at login.",
		"[Installer]: The nameplate layout keeps its side elements apart: the raid marker sits above the name, the elite icon left of the level, the quest icon at the top right corner and the crowd control auras behind the target arrow.",
		"[Installer]: Opening the installer with a controller brings up the gamepad cursor right away.",
		"[Locales]: The German translation is complete.",
		"[Locales]: Terms MerathilisUI shares with ElvUI show ElvUI's translation again instead of English or a different wording, in ElvUI too.",
		"[NamePlates]: Enemy Forces moved to the top right corner of the health bar, clear of the target arrow and the crowd control auras.",
		"[NamePlates]: The target arrows move out of the way while a castbar icon would cover them.",
		"[Options]: Many option pages now use cards: module switches show their description and icon, credits and info texts sit in cards, and simple toggles are grouped into two-column grids.",
		"[Options]: The Tags page shows a preview of the name gradient tag on sample unit frames.",
		"[Options]: The two Profiles pages are merged: Import/Export and Auto Copy Private Profile moved from Advanced Settings into the main Profiles page, whose font tab is now called Fonts.",
		"[Options]: Most module pages show a live preview that follows your settings, among them the nameplate and unitframe elements, Cursor, Vehicle Bar, Panels, Tooltip buffs, Name Hover, Loot Roll, Movement Alert, Tracker, Buff Reminder, Location Panel, Chat Sidebar and the Specialization Bar.",
	},
}
