local LSM = LibStub('LibSharedMedia-3.0')

if LSM == nil then return end

LSM:Register('font','Merathilis Prototype', [[Interface\AddOns\MerathilisUI\media\fonts\PROTOTYPE.TTF]])
LSM:Register('font','Merathilis PrototypeRU', [[Interface\AddOns\MerathilisUI\media\fonts\PROTOTYPE_RU.TTF]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Merathilis Visitor1', [[Interface\AddOns\MerathilisUI\media\fonts\visitor1.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Merathilis Visitor2', [[Interface\AddOns\MerathilisUI\media\fonts\visitor2.ttf]])
LSM:Register('font','Merathilis Tukui', [[Interface\AddOns\MerathilisUI\media\fonts\uf_font.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Merathilis Kait', [[Interface\AddOns\MerathilisUI\media\fonts\heavy_dock_kait.ttf]])
LSM:Register('font','Merathilis ArialN', [[Interface\AddOns\MerathilisUI\media\fonts\ARIALN.ttf]])
LSM:Register('font','Merathilis Roadway', [[Interface\AddOns\MerathilisUI\media\fonts\ROADWAY.ttf]])
LSM:Register('font','Merathilis Expressway', [[Interface\AddOns\MerathilisUI\media\fonts\Expressway.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('statusbar','MerathilisFlat', [[Interface\AddOns\MerathilisUI\media\textures\Flat.tga]])
LSM:Register('statusbar','MerathilisOnePixel', [[Interface\AddOns\MerathilisUI\media\textures\OnePixel.tga]])
LSM:Register('statusbar','MerathilisMelli', [[Interface\AddOns\MerathilisUI\media\textures\Melli.tga]])
LSM:Register('statusbar','MerathilisMelliDark', [[Interface\AddOns\MerathilisUI\media\textures\MelliDark.tga]])
LSM:Register('statusbar','MerathilisEmpty', [[Interface\AddOns\MerathilisUI\media\textures\Empty.tga]])
LSM:Register('statusbar','MerathilisKait1', [[Interface\AddOns\MerathilisUI\media\textures\Kait1.tga]])
LSM:Register('statusbar','MerathilisKait2', [[Interface\AddOns\MerathilisUI\media\textures\Kait2.tga]])
LSM:Register('statusbar','MerathilisnormTex', [[Interface\AddOns\MerathilisUI\media\textures\normTex.tga]])
LSM:Register('statusbar','Merathilisblank', [[Interface\AddOns\MerathilisUI\media\textures\blank.tga]])
LSM:Register('sounds','warning', [[Interface\AddOns\MerathilisUI\media\sounds\warning.ogg]])