local MER, E, L, V, P, G = unpack(select(2, ...))
local LSM = LibStub("LibSharedMedia-3.0")

----------------------------------------------------------------------------------------
--	Core options
----------------------------------------------------------------------------------------
P["mui"] = {
	["installed"] = nil,

	["general"] = {
		["LoginMsg"] = true, -- Enable welcome message in chat
		["GameMenu"] = true, -- Enable the Styles GameMenu
		["SplashScreen"] = true, -- Enable the SplashScreen on LogIn
		["AFK"] = true, -- Enable the pimped AFK Screen
		["FlightMode"] = true, -- Enable the FlightMode
		["CombatState"] = true, -- Enable the +/- Combat Message
		["HideOrderhallBar"] = false, -- Hide the OrderHallCommandBar
		["MerchantiLevel"] = true, -- Displays the itemlevel on the Merchant Frame
		["Movertransparancy"] = .75,
		["Notification"] = {
			["enable"] = true,
			["mail"] = true,
			["vignette"] = true,
			["invites"] = true,
			["guildEvents"] = true,
		},
	},

	["colors"] = {
		["styleAlpha"] = 1,
	},

	--Media
	["media"] = {
		["fonts"] = {
			["zone"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 32,
				["outline"] = "OUTLINE",
				["width"] = 512,
			},
			["subzone"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 25,
				["outline"] = "OUTLINE",
				["offset"] = 0,
				["width"] = 512,
			},
			["pvp"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 22,
				["outline"] = "OUTLINE",
				["width"] = 512,
			},
			["mail"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 12,
				["outline"] = "NONE",
			},
			["editbox"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 12,
				["outline"] = "NONE",
			},
			["gossip"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 12,
				["outline"] = "NONE",
			},
			["objective"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 12,
				["outline"] = "NONE",
			},
			["objectiveHeader"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 12,
				["outline"] = "OUTLINE",
			},
			["questFontSuperHuge"] = {
				["font"] = "Merathilis Roboto-Black",
				["size"] = 24,
				["outline"] = "NONE",
			},
		},
	},

	["misc"] = {
		["MailInputbox"] = true, -- Resize the MailInputbox
		["moveBlizz"] = true, -- Make Blizzards Frame movable
		["tradeTabs"] = true, -- Add tabs for Professions on the Tradeskillframe
		["gmotd"] = true, -- Show a GMOTD frame
		["quest"] = false,
		["announce"] = false, -- CombatText, Skill gains
		["autoscreenshot"] = false,
		["cooldowns"] = {
			["enable"] = false,
			["size"] = 25,
			["growthx"] = "LEFT",
			["growthy"] = "UP",
			["showbags"] = true,
			["showequip"] = true,
			["showpets"] = true,
		},
		["ozcooldowns"] = {
			["enable"] = true,
			["Spacing"] = 4,
			["Size"] = 30,
			["Vertical"] = false,
			["Tooltips"] = false,
			["Announce"] = false,
			["MinimumDuration"] = 600,
			["StatusBar"] = true,
			["StatusBarTexture"] = "MerathilisBlank",
			["StatusBarTextureColor"] = { ["r"] = .24, ["g"] = .54, ["b"] = .78 },
			["DurationFont"] = "Expressway",
			["DurationFontSize"] = 14,
			["DurationFontFlag"] = "OUTLINE",
			["Mode"] = "HIDE",
			["FadeMode"] = "GreenToRed",
			["SortByDuration"] = true,
			["DurationText"] = true,
		},
	},

	["datatexts"] = {
		["rightChatTabDatatextPanel"] = true,
		["panels"] = {
			["ChatTab_Datatext_Panel"] = {
				["left"] = "Call to Arms",
				["middle"] = "Coords",
				["right"] = "Bags",
			},
		},
		["threatBar"] = {
			["enable"] = true,
			["textSize"] = 10,
		},
	},

	["systemDT"] = {
		["maxAddons"] = 25, -- Sets how many Addons to show
		["showFPS"] = true, -- Show Frames per seconds
		["showMS"] = true, -- Show Ping
		["latency"] = "home", -- Set the latency type ("home", "world")
		["showMemory"] = false, -- Show Memory usage
		["announceFreed"] = true -- Enable the Garbage Message in Chat
	},

	["databars"] = {
		["enable"] = true,
	},

	["actionbars"] = {
		["transparent"] = true,
		["buttonStyle"] = {
			["enabled"] = true,
			["texture"] = LSM:Fetch("statusbar","MerathilisGradient"),
			["alpha"] = 0.25,
			["invertedShadows"] = true,
		},
		["buttonBorder"] = {
			["enabled"] = true,
			["color"] = {r = .9, g = .7, b = 0, a = .7},
		},
	},

	["unitframes"] = {
		["groupinfo"] = true,
		["player"] = {
			["detachPortrait"] = false,
			["portraitWidth"] = 110,
			["portraitHeight"] = 85,
			["portraitShadow"] = false,
			["portraitTransparent"] = true,
			["portraitStyle"] = false,
			["portraitStyleHeight"] = 6,
			["portraitFrameStrata"] = "MEDIUM",
		},
		["target"] = {
			["detachPortrait"] = false,
			["getPlayerPortraitSize"] = true,
			["portraitWidth"] = 110,
			["portraitHeight"] = 85,
			["portraitShadow"] = false,
			["portraitTransparent"] = true,
			["portraitStyle"] = false,
			["portraitStyleHeight"] = 6,
			["portraitFrameStrata"] = "MEDIUM",
		},
		["infoPanel"] = {
			["fixInfoPanel"] = true,
		},
		["misc"] = {
			["portraitTransparency"] = 0.70,
		},
		["AuraIconText"] = {
			["durationTextPos"] = "CENTER",
			["durationTextOffsetX"] = 0,
			["durationTextOffsetY"] = 0,
			["stackTextPos"] = "BOTTOMRIGHT",
			["stackTextOffsetX"] = 1,
			["stackTextOffsetY"] = 2,
			["hideDurationText"] = false,
			["hideStackText"] = false,
			["durationFilterOwner"] = false,
			["durationThreshold"] = -1,
			["stackFilterOwner"] = false,
		},
		["AuraIconSpacing"] = {
			["spacing"] = 1,
			["units"] = {
				["player"] = true,
				["target"] = true,
				["targettarget"] = true,
				["targettargettarget"] = true,
				["focus"] = true,
				["focustarget"] = true,
				["pet"] = true,
				["pettarget"] = true,
				["arena"] = true,
				["boss"] = true,
				["party"] = true,
				["raid"] = true,
				["raid40"] = true,
				["raidpet"] = true,
				["tank"] = true,
				["assist"] = true,
			},
		},
	},

	["locPanel"] = {
		["enable"] = true,
		["autowidth"] = false,
		["width"] = 245,
		["height"] = 21,
		["linkcoords"] = true,
		["template"] = "Transparent",
		["font"] = "Merathilis Roboto-Black",
		["fontSize"] = 11,
		["fontOutline"] = "OUTLINE",
		["throttle"] = 0.2,
		["format"] = "%.0f",
		["zoneText"] = true,
		["colorType"] = "REACTION",
		["colorType_Coords"] = "DEFAULT",
		["customColor"] = {r = 1, g = 1, b = 1 },
		["customColor_Coords"] = {r = 1, g = 1, b = 1 },
		["combathide"] = false,
		["portals"] = {
			["enable"] = true,
			["HSplace"] = true,
			["customWidth"] = false,
			["customWidthValue"] = 200,
			["justify"] = "LEFT",
			["cdFormat"] = "DEFAULT",
		},
	},

	["raidmarkers"] = {
		["enable"] = true,
		["visibility"] = "INPARTY",
		["customVisibility"] = "[noexists, nogroup] hide; show",
		["backdrop"] = false,
		["buttonSize"] = 18,
		["spacing"] = 2,
		["orientation"] = "HORIZONTAL",
		["modifier"] = "shift-",
		["reverse"] = false,
	},

	["tooltip"] = {
		["achievement"] = true,
		["petIcon"] = true,		-- Add an Icon for battle pets on the tooltip
		["factionIcon"] = true, -- Add a faction icon on the tooltip
		["modelIcon"] = false, -- Add a model on the Tooltip
	},

	["error"] = {
		["black"] = true,
		["combat"] = false,
		["white"] = false,
	},

	["uiButtons"] = {
		["enabled"] = true,
		["style"] = "classic",
		["strata"] = "MEDIUM",
		["level"] = 5,
		["transparent"] = "Default",
		["size"] = 17,
		["mouse"] = false,
		["menuBackdrop"] = false,
		["dropdownBackdrop"] = false,
		["orientation"] = "vertical",
		["spacing"] = 3,
		["point"] = "TOPLEFT",
		["anchor"] = "TOPRIGHT",
		["xoffset"] = 0,
		["yoffset"] = 0,
		["visibility"] = "show",
		["customroll"] = {
			["min"] = "1",
			["max"] = "50",
		},
		["Config"] = {
			["enabled"] = false,
			["called"] = "Reload",
		},
		["Addon"] = {
			["enabled"] = false,
			["called"] = "Manager",
		},
		["Status"] = {
			["enabled"] = false,
			["called"] = "AFK",
		},
		["Roll"] = {
			["enabled"] = false,
			["called"] = "Hundred",
		},
	},

	["NameplateAuras"] = {
		["spellInfo"] = {}
	},

	-- db
	["dbCleaned"] = false
}

G["nameplate"]["spellListDefault"] = {
	['visibility'] = 3,
	['width'] = 32,
	['height'] = 14,
	['lockaspect'] = false,
	['text'] = 12,
	['flashTime'] = 3,
	['firstLoad'] = true,
	['defaultSpellList'] = {
		["Massenumschlingung"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Mächtiger Hieb"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Schockwelle"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Mantel der Schatten"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Abschreckung"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Todesmantel"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Verwandlung"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Nethersturmflagge"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 70,
			["text"] = 16,
			["visibility"] = 1,
			["width"] = 70,
		},
		["Hammer der Gerechtigkeit"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Ring des Frosts"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Sonnenstrahl"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Stille"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Winterschlaf"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Erschütternder Schlag"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Göttlicher Schutz"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Blenden"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Böses vertreiben"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Verbannen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Strangulieren"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Verführung"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Antimagische Hülle"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Sprinten"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Eisblock"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Unterdrückender Schuss"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Nagen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Zehrende Kälte"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 16,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Eiskältefalle"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Wirbelsturm"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Gottesschild"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Drohruf"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Hand des Schutzes"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Entwaffnen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Schildwall"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Ruf des Meisters"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Streuschuss"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Flagge der Horde"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 70,
			["text"] = 16,
			["visibility"] = 1,
			["width"] = 70,
		},
		["Kopfnuss"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Schutzgeist"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Tieffrieren"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Hand der Freiheit"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Psychisches Entsetzen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Schmerzunterdrückung"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Dispersion"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Verhexen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Lichritter"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Schreckensgeheul"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 16,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Zerlegen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Wyverngift"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Griff der Natur"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Eisige Gegenwehr"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Baumrinde"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Entrinnen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Gedankenkontrolle"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Allianzflagge"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 70,
			["text"] = 16,
			["visibility"] = 1,
			["width"] = 70,
		},
		["Wütende Regeneration"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Spurt"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Anregen"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 40,
			["text"] = 12,
			["visibility"] = 1,
			["width"] = 40,
		},
		["Furcht"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 16,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Buße"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["School Lockout"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Wucherwurzeln"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Lichtexplosion"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
		["Aschewelle"] = {
			["lockAspect"] = true,
			["flashTime"] = 3,
			["height"] = 50,
			["text"] = 14,
			["visibility"] = 1,
			["width"] = 50,
		},
	}
}

G["nameplate"]["spellList"] = {}