local MER, F, E, I, V, P, G, L = unpack(ElvUI_MerathilisUI)

V.general = {
	install_complete = nil,
}

V.misc = {
	reshiiWrapsUpgrade = true,
	moveFrames = {
		enable = true,
		elvUIBags = true,
		tradeSkillMasterCompatible = true,
		rememberPositions = false,
		framePositions = {},
	},
}

V.quest = {
	objectiveTracker = {
		enable = true,
		noDash = true,
		colorfulProgress = true,
		percentage = false,
		colorfulPercentage = false,
		backdrop = {
			enable = false,
			transparent = true,
			topLeftOffsetX = 0,
			topLeftOffsetY = 0,
			bottomRightOffsetX = 0,
			bottomRightOffsetY = 0,
		},
		header = {
			name = E.db.general.font,
			size = E.db.general.fontSize + 2,
			style = "SHADOWOUTLINE",
			classColor = false,
			color = { r = 1, g = 1, b = 1 },
			shortHeader = true,
		},
		cosmeticBar = {
			enable = true,
			texture = "ElvUI Norm1",
			widthMode = "ABSOLUTE",
			heightMode = "ABSOLUTE",
			width = 250,
			height = 2,
			offsetX = 0,
			offsetY = -12,
			border = "SHADOW",
			borderAlpha = 1,
			color = {
				mode = "GRADIENT",
				normalColor = { r = 0.000, g = 0.659, b = 1.000, a = 1 },
				gradientColor1 = { r = 0.32941, g = 0.52157, b = 0.93333, a = 1 },
				gradientColor2 = { r = 0.25882, g = 0.84314, b = 0.86667, a = 1 },
			},
		},
		title = {
			name = E.db.general.font,
			size = E.db.general.fontSize + 1,
			style = "SHADOWOUTLINE",
		},
		info = {
			name = E.db.general.font,
			size = E.db.general.fontSize,
			style = "SHADOWOUTLINE",
		},
		titleColor = {
			enable = true,
			classColor = false,
			customColorNormal = { r = 0.000, g = 0.659, b = 1.000 },
			customColorHighlight = { r = 0.282, g = 0.859, b = 0.984 },
		},
		infoColor = {
			enable = false,
			classColor = false,
			customColorNormal = { r = 0.842, g = 0.815, b = 0.677 },
			customColorHighlight = { r = 0.992, g = 0.965, b = 0.827 },
		},
		menuTitle = {
			enable = true,
			classColor = false,
			color = { r = 0.000, g = 0.659, b = 1.000 },
			font = {
				name = E.db.general.font,
				size = E.db.general.fontSize,
				style = "SHADOWOUTLINE",
			},
		},
	},
}

V.skins = {
	enable = true,
	shadowOverlay = false,
	shadow = {
		enable = true,
		increasedSize = 0,
		color = {
			r = 0,
			g = 0,
			b = 0,
		},
	},
	widgets = {
		button = {
			enable = true,
			backdrop = {
				enable = true,
				texture = "ElvUI Norm1",
				classColor = false,
				color = { r = 0, g = 0.752, b = 0.980 },
				removeBorderEffect = true,
				animation = {
					type = "fade",
					duration = 0.2,
					alpha = 1,
					fadeEase = "quadratic",
					fadeEaseInvert = false,
				},
			},
			selected = {
				enable = true,
				backdropClassColor = false,
				backdropColor = { r = 0.322, g = 0.608, b = 0.961 },
				backdropAlpha = 0.4,
				borderClassColor = false,
				borderColor = { r = 0.145, g = 0.353, b = 0.698 },
				borderAlpha = 1,
			},
			text = {
				enable = true,
				font = {
					name = E.db.general.font,
					style = "SHADOWOUTLINE",
				},
			},
		},
		tab = {
			enable = true,
			backdrop = {
				enable = true,
				texture = "ElvUI Norm1",
				classColor = false,
				color = { r = 0, g = 0.752, b = 0.980 },
				animation = {
					type = "fade",
					duration = 0.2,
					alpha = 1,
					fadeEase = "quadratic",
					fadeEaseInvert = false,
				},
			},
			selected = {
				enable = true,
				texture = "ElvUI Norm1",
				backdropClassColor = false,
				backdropColor = { r = 0.322, g = 0.608, b = 0.961 },
				backdropAlpha = 0.4,
				borderClassColor = false,
				borderColor = { r = 0.145, g = 0.353, b = 0.698 },
				borderAlpha = 1,
			},
			text = {
				enable = true,
				normalClassColor = false,
				normalColor = { r = 1, g = 0.82, b = 0 },
				selectedClassColor = false,
				selectedColor = { r = 1, g = 1, b = 1 },
				font = {
					name = E.db.general.font,
					style = "SHADOWOUTLINE",
				},
			},
		},
		checkBox = {
			enable = true,
			texture = "ElvUI Norm1",
			classColor = false,
			color = { r = 0, g = 0.752, b = 0.980, a = 1 },
		},
		slider = {
			enable = true,
			texture = "ElvUI Norm1",
			classColor = false,
			color = { r = 0, g = 0.752, b = 0.980, a = 1 },
		},
		treeGroupButton = {
			enable = true,
			backdrop = {
				enable = true,
				texture = "ElvUI Norm1",
				classColor = false,
				color = { r = 0, g = 0.752, b = 0.980 },
				animation = {
					type = "fade",
					duration = 0.2,
					alpha = 1,
					fadeEase = "quadratic",
					fadeEaseInvert = false,
				},
			},
			selected = {
				enable = true,
				texture = "ElvUI Norm1",
				backdropClassColor = false,
				backdropColor = { r = 0.322, g = 0.608, b = 0.961, a = 0.75 },
				borderClassColor = false,
				borderColor = { r = 0.145, g = 0.353, b = 0.698, a = 0 },
			},
			text = {
				enable = true,
				normalClassColor = false,
				normalColor = { r = 1, g = 0.82, b = 0 },
				selectedClassColor = false,
				selectedColor = { r = 1, g = 1, b = 1 },
				font = {
					name = E.db.general.font,
					style = "SHADOWOUTLINE",
				},
			},
		},
	},
	blizzard = {
		enable = true,
		addonCompartment = true,
		arena = true,
		arenaRegistrar = true,
		character = true,
		encounterjournal = true,
		gossip = true,
		quest = true,
		questChoice = true,
		professionBook = true,
		talent = true,
		auctionhouse = true,
		friends = true,
		garrison = true,
		orderhall = true,
		contribution = true,
		artifact = true,
		collections = true,
		calendar = true,
		merchant = true,
		worldmap = true,
		pvp = true,
		achievement = true,
		tradeskill = true,
		lfg = true,
		lfguild = true,
		talkinghead = true,
		guild = true,
		objectiveTracker = true,
		addonManager = true,
		mail = true,
		raid = true,
		dressingroom = true,
		timemanager = true,
		blackmarket = true,
		guildcontrol = true,
		macro = true,
		binding = true,
		gbank = true,
		taxi = true,
		help = true,
		loot = true,
		deathRecap = true,
		communities = true,
		channels = true,
		challenges = true,
		azerite = true,
		AzeriteRespec = true,
		IslandQueue = true,
		IslandsPartyPose = true,
		BFAMissions = true,
		minimap = true,
		Scrapping = true,
		trainer = true,
		debug = true,
		inspect = true,
		socket = true,
		itemUpgrade = true,
		trade = true,
		voidstorage = true,
		AlliedRaces = true,
		GMChat = true,
		Archaeology = true,
		AzeriteEssence = true,
		itemInteraction = true,
		animaDiversion = true,
		soulbinds = true,
		covenantSanctum = true,
		covenantPreview = true,
		playerChoice = true,
		chromieTime = true,
		levelUp = true,
		covenantRenown = true,
		guide = true,
		craft = true,
		eventToast = true,
		weeklyRewards = true,
		misc = true,
		tooltip = true,
		bgmap = true,
		bgscore = true,
		barber = true,
		chatBubbles = true,
		expansionLanding = true,
		majorFactions = true,
		blizzardOptions = true,
		editor = true,
		perksProgram = true,
		uiWidget = true,
		delves = true,
		lossOfControl = true,
		petBattle = true,
		staticPopup = true,
		inputMethodEditor = true,
	},

	addonSkins = {
		enable = true,
		ace3 = true,
		acp = true,
		ace3DropdownBackdrop = true,
		abp = true,
		xiv = true,
		btwQ = true,
		bui = true,
		bs = true,
		pa = true,
		ls = true,
		dbm = true,
		cl = true,
		cbn = true,
		et = true,
		wa = true,
		waOptions = true,
		pf = true,
		au = true,
		imm = true,
		rio = true,
		omniCD = true,
		gil = true,
		bSync = true,
		pawn = true,
		sam = true,
		mmt = true,
		mys = true,
		mdt = true,
		tom = true,
		cap = true,
		rem = true,
		pbs = true,
		wqt = true,
		tle = true,
		wim = true,
		wowLua = true,
		bw = {
			enable = true,
			queueTimer = {
				enable = true,
				smooth = true,
				spark = true,
				colorLeft = { r = 0.32941, g = 0.52157, b = 0.93333, a = 1 },
				colorRight = { r = 0.25882, g = 0.84314, b = 0.86667, a = 1 },
				countDown = {
					name = I.Fonts.Primary,
					size = 16,
					style = "SHADOWOUTLINE",
					offsetX = 0,
					offsetY = -3,
				},
			},
			normalBar = {
				smooth = true,
				spark = true,
				colorOverride = true,
				colorLeft = { r = 0.32941, g = 0.52157, b = 0.93333, a = 1 },
				colorRight = { r = 0.25882, g = 0.84314, b = 0.86667, a = 1 },
			},
			emphasizedBar = {
				smooth = true,
				spark = true,
				colorOverride = true,
				colorLeft = { r = 1, g = 0.23, b = 0.0, a = 1 },
				colorRight = { r = 1, g = 0.48, b = 0.03, a = 1 },
			},
		},
		dt = {
			enable = true,
			gradientName = true,
			gradientBars = true,
		},
	},

	embed = {
		enable = false,
		toggleDirection = 1,
		mouseOver = false,
	},

	actionStatus = {
		name = E.db.general.font,
		size = 15,
		style = "SHADOWOUTLINE",
	},
	rollResult = {
		name = I.Fonts.Primary,
		size = 13,
		style = "SHADOWOUTLINE",
	},
	ime = {
		label = {
			name = E.db.general.font,
			size = 12,
			style = "SHADOWOUTLINE",
		},
		candidate = {
			name = E.db.general.font,
			size = E.db.general.fontSize,
			style = "SHADOWOUTLINE",
		},
		transparentBackdrop = false,
	},
}
